### ISSUE TITLE
Clarification and Naming Convention for Prop Values and Setters in React Components on the Python Side

### ISSUE THREAD

**Issue by kolibril13** [widgetti/ipyreact#26]
There was still an open conversation in https://github.com/widgetti/ipyreact/pull/11 regarding naming with @paddymul and @maartenbreddels.
I'm converting this to an issue, so it does not get lost.
The title of this issue was generated by ChatGPT.
<img width="782" alt="image" src="https://user-images.githubusercontent.com/44469195/236669603-f8d91a5d-2ec6-4bf9-945e-1ace3b76d977.png">

**Comment by maartenbreddels** [comment]
Did you ask gpt's opinion on on_ vs set_ ? :)

**Comment by kolibril13** [comment]
Just asked, with the prev. conversation in context, and here is the answer:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/44469195/236671242-7cbef89d-dece-4ee4-8a4a-1d29fa5d5164.png">

**Comment by maartenbreddels** [comment]
What about "does on_ give the impression that it is an event handler, vs set_ which might be a better name for a setter. Give pros and cons then give your advice"
Is this 3.5 or 4?

**Comment by kolibril13** [comment]
that's the free version gpt3.5.
<img width="732" alt="image" src="https://user-images.githubusercontent.com/44469195/236671594-139cb742-00d0-44a2-b9a1-0d5d6f47700b.png">

**Comment by maartenbreddels** [comment]
I can see from the quality of the answers it is not 4 :)
They don't really make sense, but I think set_ should be the way, what do you think?

**Comment by kolibril13** [comment]
Looking at these two examples, I think set_ is more intuitive.
```py
class MyCounterWidget(ipyreact.ReactWidget):
    _esm = """
    import * as React from "react";

    export default function MyButton({value, on_value}) {
        return <button onClick={() => on_value(value + 1)}>
            {value || 0} times clicked
        </button>
    };"""
m = MyCounterWidget()
```

```py
class MyCounterWidget(ipyreact.ReactWidget):
    _esm = """
    import * as React from "react";

    export default function MyButton({value, set_value}) {
        return <button onClick={() => set_value(value + 1)}>
            {value || 0} times clicked
        </button>
    };"""
m = MyCounterWidget()
m
```
 
but then looking at these two examples, I think on_ is more intuitive:

```py
import ipyreact
from traitlets import Int, Unicode

class Widget1(ipyreact.ReactWidget):
    my_count = Int(0).tag(sync=True)
    label = Unicode("Click me").tag(sync=True)

    def on_my_python_function(self):
        self.my_count = self.my_count + 1
        self.label = f"Clicked {self.my_count}"

    _esm = """
        import * as React from "react";

        export default function({on_my_python_function, label}) {
            return(
            <div>
                <button onClick={() => on_my_python_function()}>
                    {label}
                </button>
            </div>
            )
        };
    """
            
w1 = Widget1()
w1
```

```py
import ipyreact
from traitlets import Int, Unicode

class Widget1(ipyreact.ReactWidget):
    my_count = Int(0).tag(sync=True)
    label = Unicode("Click me").tag(sync=True)

    def set_my_python_function(self):
        self.my_count = self.my_count + 1
        self.label = f"Clicked {self.my_count}"

    _esm = """
        import * as React from "react";

        export default function({set_my_python_function, label}) {
            return(
            <div>
                <button onClick={() => set_my_python_function()}>
                    {label}
                </button>
            </div>
            )
        };
    """
            
w1 = Widget1()
w1
```

**Comment by maartenbreddels** [comment]
But they are not the same, one is setting a trait (and set_ should be used there), the otherone calls a python 'event' function, so there `on_` makes sense.
So I suggest we only change the `value, on_value` pairs to `value, set_value`, and keep the `on_some_event` names the same.

**Comment by kolibril13** [comment]
Nice, I think, then `set_value` and `on_some_event` is a great combination!

**Comment by kolibril13** [comment]
Closed by https://github.com/widgetti/ipyreact/pull/27
