### ISSUE TITLE
Ipyreact not working in classic Jupyter Notebook

### ISSUE THREAD

**Issue by kolibril13** [widgetti/ipyreact#41]
Environment setup:
```
python3.11 -m venv .venv && source .venv/bin/activate
pip install notebook
pip install ipyreact
jupyter notebook
```
When I now try running this example
```
import ipyreact

class MyExampleWidget(ipyreact.ReactWidget):
    _esm = """
    import * as React from "react";

    export default function MyButton() {
        return < button > X < /button> 
    };"""

MyExampleWidget()
```

in a classic notebook, I get this error:
<img width="1584" alt="image" src="https://github.com/widgetti/ipyreact/assets/44469195/2638cc81-728c-4f68-8915-b5e625d8f33a">

**Comment by kolibril13** [comment]
I managed to solve this issue 🎉 

The problem was that I had another jupyter notebook installation in `/opt/homebrew/bin` that I was not aware of.
I uninstalled the brew one and now `jupyter notebook` is linked to the correct jupyter notebook installation in the virtual environment. what a bug.🐞

**Comment by maartenbreddels** [comment]
welcome to jupyter with multiple environment :-D

You've earned some experience points along the way, and you can call yourself a wizard now :)

**Comment by kolibril13** [comment]
> and you can call yourself a wizard now :)

<img width="759" alt="image" src="https://github.com/widgetti/ipyreact/assets/44469195/d25ccc6d-e1bd-42de-9678-444d2ff09461">
