### ISSUE TITLE
JupyterLite not working anymore

### ISSUE THREAD

**Issue by maartenbreddels** [widgetti/ipyreact#57]
cc @kolibril13 

I don't see a Python kernel currently:
<img width="1774" alt="image" src="https://github.com/widgetti/ipyreact/assets/1765949/4cc48aa4-e627-47da-a9c8-fc9bfd0c5667">

**Comment by maartenbreddels** [comment]
Fixed in https://github.com/widgetti/ipyreact/commit/2d37b73d5ec793e90fb409f4de13096af8e65b73

(got some unrelated changes in it)

**Comment by kolibril13** [comment]
Great to hear it works again!
