### ISSUE TITLE
Cannot open example notebooks

### ISSUE THREAD

**Issue by arkarsg** [widgetti/ipyreact#60]
Hello,

I am unable to view notebooks in the `examples` folder. See below:

![image](https://github.com/widgetti/ipyreact/assets/84555527/61b11b9c-6510-467a-9479-77ed94330482)

**Comment by kolibril13** [comment]
Thanks for the report!

I can reproduce this error when opening
https://github.com/widgetti/ipyreact/blob/master/examples/full_tutorial.ipynb

Seems like this is a GitHub bug, as notebooks don't open in other projects as well:
https://github.com/Octoframes/jupyter_compare_view/blob/main/example_notebook.ipynb
https://github.com/kolibril13/jupyter-tldraw/blob/main/demo_makereal_davinci_resolve.ipynb

**Comment by arkarsg** [comment]
Okay! Doesn't seem like a problem of the repo then. I will close the issue. Thank you!

**Comment by maartenbreddels** [comment]
Thank you both for the report, and the investigation!
